version: "3.1"

services:
  sme-flyway:
    container_name: serap-flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://10.50.1.45:5432/serap_estudantes?user=postgres&password=postgres -locations='filesystem:/opt/scripts' -outOfOrder=true migrate
    volumes:
      - ./scripts:/opt/scripts
    networks:
      - sme-network
networks:
  sme-network:
    driver: bridge
    name: sme_external_network
