version: '3.4'

services:
  sme.serap.prova.api:
    image: ${DOCKER_REGISTRY-}smeserapprovaapi
    build:
      context: .
      dockerfile: src/SME.SERAp.Prova.Api/Dockerfile
    networks:
      - sme-network    
networks:
  sme-network:
    external:
      name: sme-network
    driver: bridge
