name: Docker Image Testing2
 
on:

  push:
    branches: [ _development_ ]
    paths-ignore:
    - ".github/workflows/**"  
  
  workflow_dispatch:

jobs:
   
  deploy-development:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/development' }}        
    environment:
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Redeploy
        uses: luizhpriotto/action_images@sonarscanner-v1.0
        with:
          ARGCMD: >
            echo "arg1"
            echo "arg2"
        env: 
          ENCMD: >
            echo "env1"
            echo "env2"
